### ISSUE TITLE
Error when container is no more present

### ISSUE THREAD

**Issue by lboff** [RakanNimer/react-google-charts#124]
Version: 
react-google-charts 1.5.3
react 15.2.1

Expected behaviour
No errors rised

Actual behaviour
My application render a char in a page. 
If the render is executed and I change the page I get the following error in the console

```
Unhandled rejection Error: The container #reactgooglegraph-1 is not defined.
    at gvjs_Z.gvjs_.getContainer (https://www.gstatic.com/charts/45.1/js/jsapi_compiled_default_module.js:240:313)
    at gvjs_Z.gvjs_.draw (https://www.gstatic.com/charts/45.1/js/jsapi_compiled_default_module.js:236:46)
    at t.drawChart (webpack:///./~/vx-ui-components/lib/index.js?:63:7235)
    at eval (webpack:///./~/vx-ui-components/lib/index.js?:63:3734)
From previous event:
    at t.componentDidMount (webpack:///./~/vx-ui-components/lib/index.js?:63:3716)
    at ReactCompositeComponentWrapper.invokeComponentDidMountWithTimer (webpack:///./~/react/lib/ReactCompositeComponent.js?:54:18)
    at CallbackQueue.notifyAll (webpack:///./~/react/lib/CallbackQueue.js?:67:22)
    at ReactReconcileTransaction.close (webpack:///./~/react/lib/ReactReconcileTransaction.js?:81:26)
    at ReactReconcileTransaction.closeAll (webpack:///./~/react/lib/Transaction.js?:204:25)
    at ReactReconcileTransaction.perform (webpack:///./~/react/lib/Transaction.js?:151:16)
    at ReactUpdatesFlushTransaction.perform (webpack:///./~/react/lib/Transaction.js?:138:20)
    at ReactUpdatesFlushTransaction.perform (webpack:///./~/react/lib/ReactUpdates.js?:90:38)
    at Object.flushBatchedUpdates (webpack:///./~/react/lib/ReactUpdates.js?:173:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (webpack:///./~/react/lib/Transaction.js?:204:25)
    at ReactDefaultBatchingStrategyTransaction.perform (webpack:///./~/react/lib/Transaction.js?:151:16)
    at Object.batchedUpdates (webpack:///./~/react/lib/ReactDefaultBatchingStrategy.js?:63:19)
    at Object.enqueueUpdate (webpack:///./~/react/lib/ReactUpdates.js?:201:22)
    at enqueueUpdate (webpack:///./~/react/lib/ReactUpdateQueue.js?:25:16)
    at Object.enqueueSetState (webpack:///./~/react/lib/ReactUpdateQueue.js?:209:5)
    at Connect.ReactComponent.setState (webpack:///./~/react/lib/ReactComponent.js?:64:16)
    at Connect.handleChange (webpack:///./~/react-redux/lib/components/connect.js?:301:14)
    at Object.dispatch (webpack:///./~/redux/lib/createStore.js?:186:19)
    at dispatch (<anonymous>:2:31397)

```

Here my code:
```
render() {
    
      return (<Chart
        chartType={this.props.type}
        data={this.props.data}
        options={this.props.options}
        graph_id={this.props.uuid}
        width={this.props.dimensions.width}
        height={this.props.dimensions.height}
        chartPackage= {['controls']}
        chartEvents={this.state.chart_events}
        ref={(ref) => this.GoogleChart = ref}
      />);
  }
```

Steps to reproduce
I can easily reproduce in my app. I do not have at the moment a code to let you reproduce.

Link to a git repo that reproduces bug : 
-

Question:
How I can avoid this behaviour? Is there a way to fix this issue?

**Comment by RakanNimer** [comment]
I don't have enough information to be able to say for sure but it looks like there's a problem with assigning the graph_id prop. 

Try removing graph_id props, since you're >1.0 the library should take care of assigning graph_id for you. If you need to assign it yourself , debug this.props.uuid. 

Going to close this, please feel free to re-open if your issue persists.

**Comment by lboff** [comment]
I remove graph_id but I am having the same issue.
