### ISSUE TITLE
Error when container is no more present

### ISSUE THREAD

**Issue by lboff** [RakanNimer/react-google-charts#125]
Version: 
react-google-charts 1.5.3
react 15.2.1

Expected behaviour
No errors

Actual behaviour
My application render a char in a page. 
If the render is called but I change the page before it is completed, the graph is not yer displayed, 
I get the following error in the console

```
Unhandled rejection Error: The container #reactgooglegraph-1 is not defined.
    at gvjs_Z.gvjs_.getContainer (https://www.gstatic.com/charts/45.1/js/jsapi_compiled_default_module.js:240:313)
    at gvjs_Z.gvjs_.draw (https://www.gstatic.com/charts/45.1/js/jsapi_compiled_default_module.js:236:46)
    at t.drawChart (webpack:///./~/vx-ui-components/lib/index.js?:63:7235)
    at eval (webpack:///./~/vx-ui-components/lib/index.js?:63:3734)
From previous event:
    at t.componentDidMount (webpack:///./~/vx-ui-components/lib/index.js?:63:3716)
    at ReactCompositeComponentWrapper.invokeComponentDidMountWithTimer (webpack:///./~/react/lib/ReactCompositeComponent.js?:54:18)
    at CallbackQueue.notifyAll (webpack:///./~/react/lib/CallbackQueue.js?:67:22)
    at ReactReconcileTransaction.close (webpack:///./~/react/lib/ReactReconcileTransaction.js?:81:26)
    at ReactReconcileTransaction.closeAll (webpack:///./~/react/lib/Transaction.js?:204:25)
    at ReactReconcileTransaction.perform (webpack:///./~/react/lib/Transaction.js?:151:16)
    at ReactUpdatesFlushTransaction.perform (webpack:///./~/react/lib/Transaction.js?:138:20)
    at ReactUpdatesFlushTransaction.perform (webpack:///./~/react/lib/ReactUpdates.js?:90:38)
    at Object.flushBatchedUpdates (webpack:///./~/react/lib/ReactUpdates.js?:173:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (webpack:///./~/react/lib/Transaction.js?:204:25)
    at ReactDefaultBatchingStrategyTransaction.perform (webpack:///./~/react/lib/Transaction.js?:151:16)
    at Object.batchedUpdates (webpack:///./~/react/lib/ReactDefaultBatchingStrategy.js?:63:19)
    at Object.enqueueUpdate (webpack:///./~/react/lib/ReactUpdates.js?:201:22)
    at enqueueUpdate (webpack:///./~/react/lib/ReactUpdateQueue.js?:25:16)
    at Object.enqueueSetState (webpack:///./~/react/lib/ReactUpdateQueue.js?:209:5)
    at Connect.ReactComponent.setState (webpack:///./~/react/lib/ReactComponent.js?:64:16)
    at Connect.handleChange (webpack:///./~/react-redux/lib/components/connect.js?:301:14)
    at Object.dispatch (webpack:///./~/redux/lib/createStore.js?:186:19)
    at dispatch (<anonymous>:2:31397)

```
Moreover...
If the render completely executed and I change the page after it is completed, once I've changed the page, everytime I resize the windows
I get the following error in the console

```
Uncaught Error: google-visualization-errors: container is null
    at Object.gvjs_T.Kc (jsapi_compiled_default_module.js:103)
    at t.updateDataTable (index.js:63)
    at t.drawChart (index.js:63)
    at t.onResize (index.js:63)
```

Here my code:
```
render() {
    
      return (<Chart
        chartType={this.props.type}
        data={this.props.data}
        options={this.props.options}
        graph_id={this.props.uuid}
        width={this.props.dimensions.width}
        height={this.props.dimensions.height}
        chartPackage= {['controls']}
        chartEvents={this.state.chart_events}
        ref={(ref) => this.GoogleChart = ref}
      />);
  }
```
I tried with and without the graph_id.

Steps to reproduce
I can easily reproduce in my app. I do not have yet a example you can play with but I could share with you my desktop.

Link to a git repo that reproduces bug : 
No

Question:
How I can avoid this behaviour? Is there a way to fix this issue?

P.S. Please do not close the issue... leave it open so we can discuss over it.

**Comment by youngzhaosignifyd** [comment]
@lboff @RakanNimer:

I think this is a bug: 

In `componentDidMount`, the `googleChartLoader` loads the google charts js file and draws the chart when the promise is resolved:
https://github.com/RakanNimer/react-google-charts/blob/master/src/components/Chart.js#L49

But in `componentWillUnmount`, there is no logic to `cancel` the promise so the drawChart will be called even if the Chart component is unmounted. 

So the javascript error happens when you unmount the Chart before the loadjs resolves. 

I think we should set a tag in componentWillUnmount like this: 

```
componentWillUnmount() { 
  this.unmounted = true; 
  ...
}
```

And check `this.unmounted` in the resolved promise OR in drawChart
```
drawChart() {
  if (this.unmounted) return;
  ...
}
```

OR 

```
componentDidMount() {
    debug('componentDidMount');
    if (typeof window === 'undefined') {
      return;
    }
    if (this.props.loadCharts) {
      googleChartLoader.init(this.props.chartPackages, this.props.chartVersion).then(() => {
        if (this.unmounted) return;
        this.drawChart();
      });
      ...
    } else {
      this.drawChart();
    }
  }
```

Right now my work-around is to set `loadCharts=false` and handle the loadjs logic inside my own app. In the wrapper component I add some logic to load the google chart js BEFORE I mount the Chart component.
https://github.com/RakanNimer/react-google-charts/blob/master/src/components/Chart.js#L428
https://github.com/RakanNimer/react-google-charts/blob/master/src/components/GoogleChartLoader.js#L21

**Comment by RakanNimer** [comment]
Hello !

Thanks for opening up the issue,

I think @youngzhaosignifyd is right, we need to either setup a way to *cancel* the promise. Since native promises are not cancelable, best idea is to what you suggested.

Interesting in preparing a PR ? I'd be very happy to merge and publish it to npm.

All the best

**Comment by abalmush** [comment]
Guys is this fix already released?
